//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AiInterfaces
{
    [Serializable]
    public class PedestrianDetectionRequest : Message
    {
        public const string k_RosMessageName = "ai_interfaces/PedestrianDetection";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.ImageMsg image;

        public PedestrianDetectionRequest()
        {
            this.image = new Sensor.ImageMsg();
        }

        public PedestrianDetectionRequest(Sensor.ImageMsg image)
        {
            this.image = image;
        }

        public static PedestrianDetectionRequest Deserialize(MessageDeserializer deserializer) => new PedestrianDetectionRequest(deserializer);

        private PedestrianDetectionRequest(MessageDeserializer deserializer)
        {
            this.image = Sensor.ImageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.image);
        }

        public override string ToString()
        {
            return "PedestrianDetectionRequest: " +
            "\nimage: " + image.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
