//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AiInterfaces
{
    [Serializable]
    public class PedestrianDetectionResponse : Message
    {
        public const string k_RosMessageName = "ai_interfaces/PedestrianDetection";
        public override string RosMessageName => k_RosMessageName;

        public bool stop;

        public PedestrianDetectionResponse()
        {
            this.stop = false;
        }

        public PedestrianDetectionResponse(bool stop)
        {
            this.stop = stop;
        }

        public static PedestrianDetectionResponse Deserialize(MessageDeserializer deserializer) => new PedestrianDetectionResponse(deserializer);

        private PedestrianDetectionResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stop);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stop);
        }

        public override string ToString()
        {
            return "PedestrianDetectionResponse: " +
            "\nstop: " + stop.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
